### ISSUE TITLE
TypeError after typing node index.js

### ISSUE THREAD

**Issue by ooga-booga123** [nftdevs/generate-nfts#15]
anyopne know how to solve this?

C:\Users\Adam\Desktop\generate-nfts-main>node index.js
(node:11216) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:194
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:194:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:193:10)
    at C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:374:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:373:17)
    at C:\Users\Adam\Desktop\generate-nfts-main\index.js:6:3
    at Object.<anonymous> (C:\Users\Adam\Desktop\generate-nfts-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by pmogollons** [comment]
This issue is most likely caused by adding `-` in the name of files. You cann remove it or change the dna delimitter.
