### ISSUE TITLE
unexpected token error in main.js

### ISSUE THREAD

**Issue by syntax-co** [nftdevs/generate-nfts#29]
layerObj.options?.["displayName"] != undefined
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\muncr\Desktop\projects-v2\in_progress\CCC\nft-generation\generate-nfts-main\index.js:2:39)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by syntax-co** [comment]
no changes had been made to the file which I found interesting.

**Comment by syntax-co** [comment]
found issue, was not working with correct node version. was using 12.8.0 and tried 18.2.0 with even more issues but then went back a little to 17.2.0 and it worked fine, sorry
