### ISSUE TITLE
index.s

### ISSUE THREAD

**Issue by JCUN23** [nftdevs/generate-nfts#4]
![Screenshot 2022-01-12 171501](https://user-images.githubusercontent.com/55635300/149231519-c7913ae8-d6e0-4fb2-82bc-f4363d7add82.png)

**Comment by Rachid-Jedata** [comment]
I've got the same problem

**Comment by ooga-booga123** [comment]
anyone know how to solve this:

C:\Users\Adam\Desktop\generate-nfts-main>node index.js
(node:11216) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:194
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:194:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:193:10)
    at C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:374:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\Users\Adam\Desktop\generate-nfts-main\src\main.js:373:17)
    at C:\Users\Adam\Desktop\generate-nfts-main\index.js:6:3
    at Object.<anonymous> (C:\Users\Adam\Desktop\generate-nfts-main\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

**Comment by izerr-alt** [comment]
> ![Screenshot 2022-01-12 171501](https://user-images.githubusercontent.com/55635300/149231519-c7913ae8-d6e0-4fb2-82bc-f4363d7add82.png)

hey did you deal with it? have the same problem

**Comment by izerr-alt** [comment]
> Hey mate, No I didn’t, i gave up and used a hashlips tutorial, ill link it below (its much better and her goes properly in depth about each aspect of the code) https://youtu.be/fzH7Gjadmj0 Hope it helps!
> […](#)
> On 12 Feb 2022, at 23:25, izerr-alt ***@***.***> wrote: ﻿ hey did you deal with it? have the same problem — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

Bro... You helped me to fix the problem. After watching you video i've just installed nodejs 14.17.6 and put the tick "Allow nodejs to download and install addictional content" or something like this AND IT WOREKD lmao!! 0 errs

**Comment by boky123** [comment]
I got the same problem also
